import { useEffect, useState, type FormEvent } from 'react';
import { Copy, Pencil, Plus } from 'lucide-react';
import { Button, Card, ConfirmDialog, EmptyState, Field, Input, LoadingSkeleton, PageHeader, SearchInput, Select, TableWrap, Textarea } from '../components';
import { productsApi, type Product, type ProductInput } from '../products-api';
import { money } from '../lib'; import { useAuth } from '../useAuth';

const blank: ProductInput = { name: '', description: null, sku: null, type: 'SERVICE', unit: 'hour', defaultQuantity: 1, unitPriceMinor: 0, vatRate: 25, currency: 'NOK', category: null, active: true };

function ProductDialog({ product, close, saved }: { product?: Product; close: () => void; saved: (product: Product) => void }) {
  const [form, setForm] = useState<ProductInput>(product ? { ...product } : blank); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  const submit = async (event: FormEvent) => { event.preventDefault(); setBusy(true); setError(''); try { saved(product ? await productsApi.update(product.id, form) : await productsApi.create(form)); close(); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Could not save'); } finally { setBusy(false); } };
  return <div className="modal-backdrop"><section className="modal-card" role="dialog" aria-modal="true"><div className="modal-head"><div><h2>{product ? 'Edit' : 'Add'} product or service</h2><p>Reusable defaults for invoice lines.</p></div></div><form onSubmit={(event) => void submit(event)}><div className="form-grid"><Field label="Name"><Input autoFocus required value={form.name} onChange={(e) => setForm({...form,name:e.target.value})}/></Field><Field label="Type"><Select value={form.type} onChange={(e)=>setForm({...form,type:e.target.value as ProductInput['type']})}><option value="SERVICE">Service</option><option value="PRODUCT">Product</option></Select></Field><Field label="SKU"><Input value={form.sku ?? ''} onChange={(e)=>setForm({...form,sku:e.target.value||null})}/></Field><Field label="Category"><Input value={form.category ?? ''} onChange={(e)=>setForm({...form,category:e.target.value||null})}/></Field><Field label="Unit"><Input value={form.unit} onChange={(e)=>setForm({...form,unit:e.target.value})}/></Field><Field label="Default quantity"><Input type="number" step="0.0001" min="0.0001" value={form.defaultQuantity} onChange={(e)=>setForm({...form,defaultQuantity:Number(e.target.value)})}/></Field><Field label="Unit price"><Input type="number" min="0" step="0.01" value={form.unitPriceMinor/100} onChange={(e)=>setForm({...form,unitPriceMinor:Math.round(Number(e.target.value)*100)})}/></Field><Field label="VAT rate"><Input type="number" min="0" max="100" step="0.01" value={form.vatRate} onChange={(e)=>setForm({...form,vatRate:Number(e.target.value)})}/></Field></div><Field label="Description"><Textarea rows={3} value={form.description ?? ''} onChange={(e)=>setForm({...form,description:e.target.value||null})}/></Field>{error&&<p className="form-error">{error}</p>}<div className="modal-actions"><Button type="button" variant="secondary" onClick={close}>Cancel</Button><Button disabled={busy}>{busy?'Saving…':'Save'}</Button></div></form></section></div>;
}

export function ProductsPage() { const { profile } = useAuth(); const canManage = profile?.company.role==='OWNER'||profile?.company.role==='ADMIN'; const [items,setItems]=useState<Product[]>([]); const [search,setSearch]=useState(''); const [type,setType]=useState(''); const [loading,setLoading]=useState(true); const [editing,setEditing]=useState<Product|null>(); const [archive,setArchive]=useState<Product>();
  useEffect(()=>{let active=true; const timer=setTimeout(()=>productsApi.list(search,type).then(result=>active&&setItems(result)).finally(()=>active&&setLoading(false)),200); return()=>{active=false;clearTimeout(timer)}},[search,type]);
  const upsert=(item:Product)=>setItems(current=>[...current.filter(x=>x.id!==item.id),item].sort((a,b)=>a.name.localeCompare(b.name)));
  return <div className="page"><PageHeader title="Products & Services" description="Reusable catalogue items for consistent invoicing." action={canManage?<Button onClick={()=>setEditing(null)}><Plus size={16}/>Add item</Button>:undefined}/><Card><div className="filterbar"><SearchInput value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search products…"/><Select value={type} onChange={e=>setType(e.target.value)}><option value="">All types</option><option value="SERVICE">Services</option><option value="PRODUCT">Products</option></Select></div>{loading?<LoadingSkeleton/>:items.length?<TableWrap><table><thead><tr><th>Name</th><th>Type</th><th>Unit</th><th>VAT</th><th className="number">Price</th><th/></tr></thead><tbody>{items.map(x=><tr key={x.id}><td><b>{x.name}</b><br/><small>{x.sku||x.category||''}</small></td><td>{x.type.toLowerCase()}</td><td>{x.unit}</td><td>{x.vatRate}%</td><td className="number">{money(x.unitPriceMinor/100,x.currency)}</td><td>{canManage&&<div className="row-actions"><Button variant="ghost" onClick={()=>setEditing(x)}><Pencil size={15}/></Button><Button variant="ghost" onClick={()=>void productsApi.duplicate(x.id).then(upsert)}><Copy size={15}/></Button><Button variant="ghost" onClick={()=>setArchive(x)}>Archive</Button></div>}</td></tr>)}</tbody></table></TableWrap>:<EmptyState title="No products or services yet" description="Add reusable work, goods or subscription items."/>}</Card>{editing!==undefined&&<ProductDialog product={editing??undefined} close={()=>setEditing(undefined)} saved={upsert}/>} {archive&&<ConfirmDialog title={`Archive ${archive.name}?`} description="It will no longer appear in default invoice selection." confirmLabel="Archive item" onCancel={()=>setArchive(undefined)} onConfirm={()=>void productsApi.archive(archive.id).then(upsert).then(()=>setArchive(undefined))}/>}</div> }
